[training]
batch_size = 5
gradient_accumulation_steps = 1
drop_out = 0.1
;bert/finbert 0.1
num_workers = 0
epochs = 10
device = cuda:0
seed = 789
max_grad_norm = 10
lr = 5e-5
;bert 2e-5
;finbert 5e-5
use_strictloss = False
weight_decay = 0.0
use_marker = False

[Encoder]
encoder_type = finbert
roberta_path = D:/GraduateProject/ArkMSA/pretrained_models/roberta-large
bert_path = D:/GraduateProject/ArkMSA/pretrained_models/bert-base-uncased
finbert_path = D:/GraduateProject/ArkMSA/pretrained_models/finbert
max_length = 400
vocab_size = 50265
encoder_output_size = 768
model_type = cls

[data]
dataset_name = Stock_Twitter
task = Stock
root_dir = ./data/Stock
use_text = True
use_description = False
use_reason = False
save_name = text_only

[extra]
p_mask = 0.3
rewrite_p = 0.0
average = macro
alpha = 0.5